#!/bin/sh -e

if ! pgrep X > /dev/null; then
	echo "${0##*/}: X isn't running"
	exit 1
fi

dir=$WM_DIR/maximize

r=$(lsw -r)
sw=$(wattr w $r)
sh=$(wattr h $r)

usage() {
	echo "usage: ${0##*/} [-f] WID" >&2
	exit 1
}

toggle_maximize() {
	wattr $1 || return
	f=$(find $dir -name $1)

	case $f in
		'')
			wattr xywhi $1 > $dir/$1

			w=$((sw - WM_GAPSIZE*2 - WM_BORDERSIZE*2))
			h=$((sh - BAR_HEIGHT - WM_GAPSIZE*2 - WM_BORDERSIZE*2))

			if test -n "$BAR_BOTTOM"; then
				wtp $WM_GAPSIZE $WM_GAPSIZE $w $h $1
			else
				wtp $WM_GAPSIZE $((BAR_HEIGHT + WM_GAPSIZE)) $w $h $1
			fi
			;;
		*)
			wtp $(cat $f)
			rm -f $f
			;;
	esac
}

toggle_fullscreen() {
	wattr $1 || return
	f=$(find $dir -name $1)

	case $f in
		'')
			wattr xywhi $1 > $dir/$1
			wtp -$WM_BORDERSIZE -$WM_BORDERSIZE $sw $sh $1
			;;
		*)
			wtp $(cat $f)
			rm -f $f
			;;
	esac
}

setup() {
	mkdir -p $dir

	for f in $(find $dir -type f); do
		wattr ${f##*/} || rm -f $f
	done
}

setup

case $* in
	0x*)     toggle_maximize $1   ;;
	-f\ 0x*) toggle_fullscreen $2 ;;
	*)       usage                ;;
esac
