#!/bin/sh

if ! pgrep X > /dev/null; then
	echo "${0##*/}: X isn't running"
	exit 1
fi

r=$(lsw -r)
sw=$(wattr w $r)
sh=$(($(wattr h $r) - BAR_HEIGHT))

usage() {
	echo "usage: ${0##*/} -ctlrbTLRB WID" >&2
	exit 1
}

center() {
	if test -n "$BAR_BOTTOM"; then
		wmv -a $((sw/2 - WM_BORDERSIZE)) $((sh/2 - WM_BORDERSIZE)) $1
	else
		wmv -a $((sw/2 - WM_BORDERSIZE)) $((BAR_HEIGHT + sh/2 - WM_BORDERSIZE)) $1
	fi
}

one_half() {
	case $1 in
		-t)
			w=$((sw - WM_GAPSIZE*2 - WM_BORDERSIZE*2))
			h=$((sh/2 - WM_GAPSIZE - WM_GAPSIZE/2 - WM_BORDERSIZE*2))

			if test -n "$BAR_BOTTOM"; then
				wtp $WM_GAPSIZE $WM_GAPSIZE $w $h $2
			else
				wtp $WM_GAPSIZE $((BAR_HEIGHT + WM_GAPSIZE)) $w $h $2
			fi
			;;
		-b)
			w=$((sw - WM_GAPSIZE*2 - WM_BORDERSIZE*2))
			h=$((sh/2 - WM_GAPSIZE - WM_GAPSIZE/2 - WM_BORDERSIZE*2))
			y=$((sh - h - WM_GAPSIZE - WM_BORDERSIZE*2))

			if test -n "$BAR_BOTTOM"; then
				wtp $WM_GAPSIZE $y $w $h $2
			else
				wtp $WM_GAPSIZE $((y + BAR_HEIGHT)) $w $h $2
			fi
			;;
		-l)
			w=$((sw/2 - WM_GAPSIZE - WM_GAPSIZE/2 - WM_BORDERSIZE*2))
			h=$((sh - WM_GAPSIZE*2 - WM_BORDERSIZE*2))

			if test -n "$BAR_BOTTOM"; then
				wtp $WM_GAPSIZE $WM_GAPSIZE $w $h $2
			else
				wtp $WM_GAPSIZE $((BAR_HEIGHT + WM_GAPSIZE)) $w $h $2
			fi
			;;
		-r)
			w=$((sw/2 - WM_GAPSIZE - WM_GAPSIZE/2 - WM_BORDERSIZE*2))
			h=$((sh - WM_GAPSIZE*2 - WM_BORDERSIZE*2))
			x=$((sw - w - WM_GAPSIZE - WM_BORDERSIZE*2))

			if test -n "$BAR_BOTTOM"; then
				wtp $x $WM_GAPSIZE $w $h $2
			else
				wtp $x $((BAR_HEIGHT + WM_GAPSIZE)) $w $h $2
			fi
			;;
	esac
}

one_fourth() {
	w=$((sw/2 - WM_GAPSIZE - WM_GAPSIZE/2 - WM_BORDERSIZE*2))
	h=$((sh/2 - WM_GAPSIZE - WM_GAPSIZE/2 - WM_BORDERSIZE*2))

	case $1 in
		-T)
			if test -n "$BAR_BOTTOM"; then
				wtp $WM_GAPSIZE $WM_GAPSIZE $w $h $2
			else
				wtp $WM_GAPSIZE $((BAR_HEIGHT + WM_GAPSIZE)) $w $h $2
			fi
			;;
		-R)
			x=$((sw - w - WM_GAPSIZE - WM_BORDERSIZE*2))

			if test -n "$BAR_BOTTOM"; then
				wtp $x $WM_GAPSIZE $w $h $2
			else
				wtp $x $((BAR_HEIGHT + WM_GAPSIZE)) $w $h $2
			fi
			;;
		-L)
			y=$((sh - h - WM_GAPSIZE - WM_BORDERSIZE*2))

			if test -n "$BAR_BOTTOM"; then
				wtp $WM_GAPSIZE $y $w $h $2
			else
				wtp $WM_GAPSIZE $((y + BAR_HEIGHT)) $w $h $2
			fi
			;;
		-B)
			x=$((sw - w - WM_GAPSIZE - WM_BORDERSIZE*2))
			y=$((sh - h - WM_GAPSIZE - WM_BORDERSIZE*2))

			if test -n "$BAR_BOTTOM"; then
				wtp $x $y $w $h $2
			else
				wtp $x $((y + BAR_HEIGHT)) $w $h $2
			fi
			;;
	esac
}

case $* in
	-c\ 0x*)      center $2        ;;
	-[tlrb]\ 0x*) one_half $1 $2   ;;
	-[TLRB]\ 0x*) one_fourth $1 $2 ;;
	*)            usage            ;;
esac
